### ISSUE TITLE
[UIUX] cart 和 reservation 放 nav bar 或 hover menu

### ISSUE THREAD

**Issue by yuting1008** [guan404ming/dishcovery#100]
有兩個方式擇一（ prefer 第一個！）

1. cart 和 reservation 都放 nav bar
2. cart 和 reservation 都放 hover menu

<img width="1415" alt="Screen Shot 2024-05-24 at 8 12 51 PM" src="https://github.com/guan404ming/dishcovery/assets/105917993/7efc046c-1150-4f94-9b39-2e40a05513dd">

**Comment by yuting1008** [comment]
有兩個方式擇一（ prefer 第一個！）
1. cart 和 reservation 都放 nav bar
2. cart 和 reservation 都放 hover menu

**Comment by imbensonchiu** [comment]
Well done!
