### ISSUE TITLE
[購買剩食] 從 cart 按「確認」進入 reservation 時，並不會檢查當時的數量有沒有低於 remaining

### ISSUE THREAD

**Issue by imbensonchiu** [guan404ming/dishcovery#101]
如題

**Comment by guan404ming** [comment]
@imbensonchiu Done~ 再幫我review個感謝

**Comment by imbensonchiu** [comment]
@guan404ming  還是有 bug > <
<img width="1306" alt="image" src="https://github.com/guan404ming/dishcovery/assets/96575609/abd8f24f-ab59-45b0-ab8a-79036111aaae">

<img width="640" alt="image" src="https://github.com/guan404ming/dishcovery/assets/96575609/d387e452-ce53-4c21-99f5-771073dface5">


1. 該商品剩 2 個
2. 我先加 2 個進入 cart -> 不會被擋
3. 我再加 1 個進入 cart -> 不會被擋
4. cart 現在有 3 個，按「確認」進入 reservation -> **不會被擋**
5. Remaining 最後變 -1

**Comment by imbensonchiu** [comment]
Well done!
