### ISSUE TITLE
[刊登剩食] 一個 post / store 可以新增多個 dish

### ISSUE THREAD

**Issue by karenhsieh75** [guan404ming/dishcovery#102]
店家說他們會一次剩下很多種類的剩食，希望可以一次 post

**Comment by imbensonchiu** [comment]
@guan404ming 
Post 頁面正常
<img width="1377" alt="image" src="https://github.com/guan404ming/dishcovery/assets/96575609/dcd0f0db-8b82-41b8-8fdc-21bb7d671904">

但 My Post 裡面只有顯示 Post 的其中一個 Dish

<img width="1377" alt="image" src="https://github.com/guan404ming/dishcovery/assets/96575609/77a95c5d-a0e5-4fab-adee-cd0ebdcd71b8">

**Comment by imbensonchiu** [comment]
Well done!
