### ISSUE TITLE
[預約剩食] 預約時的數量限制有兩種

### ISSUE THREAD

**Issue by karenhsieh75** [guan404ming/dishcovery#105]
假設 post 剩 10 個，預約時
1. 如果 user 輸入 9，會顯示：should between 1-5
2. 如果 user 輸入 120，會顯示：should under 10

**Comment by yuting1008** [comment]
1. 
<img width="691" alt="Screen Shot 2024-05-24 at 8 38 09 PM" src="https://github.com/guan404ming/dishcovery/assets/105917993/c20a6cb4-a8b5-4546-b68d-f1883cce3cab">

2.
<img width="817" alt="Screen Shot 2024-05-24 at 8 36 56 PM" src="https://github.com/guan404ming/dishcovery/assets/105917993/91a7a7e3-a0bf-4549-bf03-a8ef3dbb222a">

**Comment by guan404ming** [comment]
這兩種都要保留ㄇ？還是有優先順序？

**Comment by karenhsieh75** [comment]
@guan404ming 我們覺得可以保留：The number should between 1 and "remaining".
