### ISSUE TITLE
[預約剩食] 在 store 新增某個 dish 到購物車的時候 quantity 可以被按到負的

### ISSUE THREAD

**Issue by imbensonchiu** [guan404ming/dishcovery#108]
如圖：
<img width="598" alt="image" src="https://github.com/guan404ming/dishcovery/assets/96575609/1ce6b4a5-93dd-44c7-a2aa-d3e31aac9883">

**Comment by guan404ming** [comment]
@imbensonchiu  Done~~

**Comment by imbensonchiu** [comment]
Well done!
