### ISSUE TITLE
[預約剩食] reservation 的地方各項目沒有按照店家 / 貼文分組

### ISSUE THREAD

**Issue by imbensonchiu** [guan404ming/dishcovery#109]
如圖
<img width="1306" alt="image" src="https://github.com/guan404ming/dishcovery/assets/96575609/13ff6bb4-0eef-4635-a6b8-a9874370df9f">

**Comment by guan404ming** [comment]
Done~ Help me review, thx!

**Comment by imbensonchiu** [comment]
Well done!
