### ISSUE TITLE
[購買剩食] cart 和 reservation 的關係

### ISSUE THREAD

**Issue by huangfishburger** [guan404ming/dishcovery#78]
![image](https://github.com/guan404ming/dishcovery/assets/129679328/63e6f396-e736-4002-bcd6-94e73f989ca2)

有點不明白 cart 和 reservation 的關係

1. 假設從 store 預定 item 一定會經過 cart ，再把結果放到 reservation，那 reservation 不應該可以增減 item ? 
2. 如果 reservation 不應該可以增減 item，但可以增減 post，不知道會不會有點神奇，或是因為 post 不需要在做一個 confirm 的動作?

**Comment by huangfishburger** [comment]
post 和 store 的商品都要進到 cart 裡，confirm 之後在進到 reservation，reservation 中不能增減數量。

**Comment by guan404ming** [comment]
@huangfishburger 再幫我測個感謝～

**Comment by huangfishburger** [comment]
測試成功~
