### ISSUE TITLE
[確認賣出] Finished 的訂單還可以再打勾 ＆ 右上角數字更動確認

### ISSUE THREAD

**Issue by Peng-Jen** [guan404ming/dishcovery#90]
![image](https://github.com/guan404ming/dishcovery/assets/86714764/3fdb2689-9f60-42ca-b352-4ea05233527e)

Finished 的訂單可以再打勾，並且會有一樣的回應：Reservation has been finished.
右上角的數字不確定是 Reservation 有的總和數量，還是剩餘數量，但總之他可以變多變少。
如果他是總和數量，那應該是個 bug（嗎）；如果他是剩餘數量，可能討論一下怎麼樣會變直觀？

**Comment by imbensonchiu** [comment]
**Finished 的訂單還可以再打勾** -- 已解決
右上角數字更動確認 -- 和 #85 合併，合併後問題參見 #85
