### ISSUE TITLE
[預約剩食] 在 Post Reservations 可以新增五個以上剩食

### ISSUE THREAD

**Issue by yuting1008** [guan404ming/dishcovery#93]
預約時有限定只能訂 1-5 個剩食，但在 Post Reservations 可以加超過五個。

<img width="1022" alt="Screen Shot 2024-05-24 at 1 10 27 PM" src="https://github.com/guan404ming/dishcovery/assets/105917993/e2fc066c-76f0-4e0e-b92e-f292f495edbd">
<img width="1193" alt="Screen Shot 2024-05-24 at 1 11 35 PM" src="https://github.com/guan404ming/dishcovery/assets/105917993/2e52bac1-debb-4716-98d9-25775c44d68c">

**Comment by imbensonchiu** [comment]
參見 #105
