### ISSUE TITLE
[預約剩食] 在 Cart 可以新增五個以上剩食

### ISSUE THREAD

**Issue by yuting1008** [guan404ming/dishcovery#94]
預約剩食時只能填 1-5 個，但到 Cart 之後可以加到 5 個以上。

<img width="1088" alt="Screen Shot 2024-05-24 at 1 13 08 PM" src="https://github.com/guan404ming/dishcovery/assets/105917993/ecaffb5c-eaf3-4350-a30e-dbbd90f90f60">

<img width="1207" alt="Screen Shot 2024-05-24 at 1 12 45 PM" src="https://github.com/guan404ming/dishcovery/assets/105917993/db6f514b-1585-4d85-a58d-85421a84f071">

**Comment by imbensonchiu** [comment]
參見 #105
