### ISSUE TITLE
[確認賣出] 數字應介於 1 到 5

### ISSUE THREAD

**Issue by Peng-Jen** [guan404ming/dishcovery#97]
![image](https://github.com/guan404ming/dishcovery/assets/86714764/8eb8cdbc-0646-4edf-868e-ad9b359d0815)

右上角那個數字我還是沒有很清楚代表著什麼，但應該不會是 reservation 的數量？
這個數字我從 19 一路向下減到 0 才不能再減，螢幕會跳出 "The number should between 1 and 5"（這裡也沒有 match）
我從 0 往上加，到 5 之後就不能再往上了，理由一樣是 "The number should between 1 and 5"，不過這個就比較怪了。

希望講得還算清楚！

**Comment by imbensonchiu** [comment]
已解決
