### ISSUE TITLE
[搜尋剩食]搜尋框的 placeholder 應改成 search

### ISSUE THREAD

**Issue by huangfishburger** [guan404ming/dishcovery#99]
![image](https://github.com/guan404ming/dishcovery/assets/129679328/96797e9f-ac9d-486b-912c-7ca38b458058)

目前沒有做 type 的標籤，搜尋 type 會找不到

**Comment by guan404ming** [comment]
@huangfishburger Done! help me review, thx~~

**Comment by huangfishburger** [comment]
測試成功！
